#!/usr/bin/env bash


PHARO_VM_13_DIR="/Users/toky/Documents/Pharo/vms/130-x64/Pharo.app/Contents/MacOS"
MOOSE_CI_IMAGE_PATH="/Users/toky/Documents/Pharo/images/MooseCI-1/MooseCI-1.image"


"$PHARO_VM_13_DIR"/Pharo --headless "$MOOSE_CI_IMAGE_PATH" --no-default-preferences clap moose-ci "$@"